restore handwritten show/eq instances
the reason is that using generic instance results in:

```
/dev/purescript-spec/output/Data.Generic.Rep.Show/index.js:13
var GenericShowArgs = function (genericShowArgs) {
                               ^

RangeError: Maximum call stack size exceeded
    at new GenericShowArgs (/dev/purescript-spec/output/Data.Generic.Rep.Show/index.js:13:32)
    at Object.genericShowArgsArgument (/dev/purescript-spec/output/Data.Generic.Rep.Show/index.js:20:12)
    at showGroup (/dev/purescript-spec/output/Test.Spec/index.js:241:228)
    at showGroup (/dev/purescript-spec/output/Test.Spec/index.js:241:456)
```